project:
  type: website

website:
  title: "Zhehao Hu"
  site-url: https://zzzhehao.github.io
  description: "Zhehao Hu's Personal Website"
  
  navbar: 
    tools: 
      - icon: github
        href: https://github.com/zzzhehao
        text: "GitHub"
      - icon: instagram
        href: https://instagram.com/zhehao.hu_
    search: true
    background: transparent

format: 
  html:
    theme: theme.scss