project:
  type: website
  resources: 
    - "*.jpg"
    - "*.png"
  render: 
    - "*"
    - "!comments/*"

website:
  title: "Zhehao Hu"
  site-url: https://zzzhehao.github.io
  description: "Zhehao Hu's Personal Website"
  
  navbar: 
    left: 
      - text: "Photography"
        menu: 
          - text: "Albums"
            href: gallery/gallery.qmd
          - text: "Videos"
            href: gallery/videos.qmd
          - text: "As a Photographer"
            href: gallery/asphotographer.qmd

      - text: "Research"
        menu:
          - text: "Posts"
            href: research/posts.qmd
          - text: "As a Biology Student"
            href: research/asbiologist.qmd
      - text: "Personal"
        menu:
          - text: "About Me"
            href: personal/aboutme.qmd

    tools: 
      - icon: github
        href: https://github.com/zzzhehao
        text: "GitHub"
      - icon: instagram
        href: https://instagram.com/zhehao.hu_
    search: true
    background: transparent

  # body-footer: |
  #   © 2024 Zhehao Hu. Source code available at [github.com](https://github.com/zzzhehao).

format: 
  html:
    theme: 
      - theme/style.scss
      - theme/custom-nav.scss