project:
  type: website
  render: 
    - "*"
    - "!comments/*"

website:
  title: "Zhehao Hu"
  site-url: https://zzzhehao.github.io
  description: "Zhehao Hu's Personal Website"
  
  navbar: 
    left: 
      - text: "About me"
        menu: 
          - text: "Personal"
            href: personal/aboutme.qmd
          - text: "As a Biology Student"
            href: research/asbiologist.qmd
          - text: "As a Photographer"
            href: gallery/asphotographer.qmd
      - text: "Gallery"
        href: gallery/gallery.qmd
      - text: "Posts"
        href: research/posts.qmd
    tools: 
      - icon: github
        href: https://github.com/zzzhehao
        text: "GitHub"
      - icon: instagram
        href: https://instagram.com/zhehao.hu_
    search: true
    background: transparent

  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    left: "&copy; By Zhehao Hu, 2024. Source code available at [github.com](https://github.com/zzzhehao/zzzhehao.github.io/tree/main)"
    background: $black
    border: false

format: 
  html:
    theme: color-code.scss