project:
  type: website
  resources: 
    - "*.jpg"
    - "*.png"
    - "*.pdf"
  render: 
    - "*"
    - "!comments/*"
  execute-dir: project

bibliography:
  - ../../Obsidian/Cafe AgX HQ 2.0/003 Management/Research & Career/research-writing/bib/biology-research.bib

website:
  title: "Zhehao Hu"
  site-url: https://zzzhehao.github.io/
  site-path: ./
  description: "Zhehao Hu's Personal Website"
  draft-mode: unlinked
  
  navbar: 
    left: 
      - text: "Photography"
        menu: 
          - text: "Albums"
            href: gallery/gallery.qmd
          - text: "Color palette"
            href: photography/color_palette.qmd
          # - text: "Videos"
          #   href: gallery/videos.qmd
          # - text: "As a Photographer"
          #   href: gallery/asphotographer.qmd

      - text: "Research"
        menu:
          - text: "Posts"
            href: biology-research/index.qmd
          - text: "As a Biology Student"
            href: biology-research/asbiologist.qmd
      - text: "Personal"
        menu:
          - text: "About Me"
            href: personal/aboutme.qmd
      - text: "What's new"
        href: news.qmd

    tools: 
      - icon: github
        href: https://github.com/zzzhehao
        text: "GitHub"
      - icon: instagram
        href: https://instagram.com/zhehao.hu_
    search: true
    background: transparent

  # body-footer: |
  #   © 2024 Zhehao Hu. Source code available at [github.com](https://github.com/zzzhehao).
format: 
  html:
    highlight-style: arrow-light
    theme: 
      light: [theme/style.scss, theme/custom-nav.scss, theme/callouts.scss]
      dark: [theme/style-dark.scss, theme/custom-nav-dark.scss, theme/callouts-dark.scss]
execute: 
  freeze: auto