project:
  type: website
  render: 
    - "*"
    - "!comments/*"

website:
  title: "Zhehao Hu"
  site-url: https://zzzhehao.github.io
  description: "Zhehao Hu's Personal Website"
  
  navbar: 
    left: 
      - text: "About me"
        menu: 
          - personal/aboutme.qmd
          - research/asbiologist.qmd
          - gallery/asphotographer.qmd
      - text: "Gallery"
        href: gallery/gallery.qmd
      - text: "Posts"
        href: research/posts.qmd
    tools: 
      - icon: github
        href: https://github.com/zzzhehao
        text: "GitHub"
      - icon: instagram
        href: https://instagram.com/zhehao.hu_
    search: true
    background: transparent

  # sidebar: 
  #   style: "docked"
  #   logo: "images/happy_hu.jpg"
  #   pinned: true
  #   alignment: center
  #   background: $Keloe-2-rgba
  #   collapse-level: 1
  #   contents: 
  #     - href: index.qmd
  #       text: Home
  #     - href: about.qmd
  #       text: About me

  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    left: "&copy; By Zhehao Hu, 2024"
    center: "Source code of this website is available at [github.com/zzzhehao](https://github.com/zzzhehao/zzzhehao.github.io/tree/main)"
    background: $Keloe-1-rgba
    border: false

format: 
  html:
    theme: color-code.scss