project:
  type: website
  resources: 
    - "*.jpg"
    - "*.png"
    - "*.pdf"
    - "*.json"
    - "shinylive-sw.js"
  render: 
    - "*"
    - "!comments/*"
    - "!draft*.qmd"
  # pre-render: 
  #   - gallery/gallery-meta.py
  execute-dir: project
  output-dir: _site

bibliography:
  - ../../zzzhehao/80-89 Resources/82 References/80.01 BibTex Bibliography/biology-research-master.bib

website:
  title: "Zhehao Hu"
  site-url: https://zzzhehao.github.io/
  site-path: ./
  description: "Zhehao Hu's Personal Website"
  draft-mode: unlinked
  google-analytics: "G-R0FB3TL998"

  navbar: 
    left: 
      - text: "Photography"
        menu: 
          - text: "Albums"
            href: gallery/gallery.qmd
          - text: "Blue Marbles"
            href: gallery/blue-marble/blue-marble.qmd
          - text: "Motion Picture"
            href: gallery/motion-pictures.qmd
          - text: "Color palette"
            href: photography/color_palette.qmd

      - text: "Research"
        menu:
          - text: "Posts"
            href: biology-research/index.qmd
          - text: "Feed"
            href: biology-research/feeds/feed.qmd
          - text: "As a Biology Student"
            href: biology-research/asbiologist.qmd
          - text: "CV"
            href: biology-research/CV_Zhehao_Hu.pdf

      - text: "About me"
        href: about.qmd
      - text: "What's new"
        href: news.qmd

    tools: 
      - icon: github
        href: https://github.com/zzzhehao
        text: "GitHub"
      - icon: instagram
        href: https://instagram.com/zhehao.hu_
    search: true
    background: transparent

format: 
  html:
    highlight-style: arrow-light
    theme: 
      light: [theme/global-setting.scss, theme/style.scss, theme/custom-nav.scss, theme/callouts.scss, theme/sort-ui.scss]
      dark: [theme/global-setting.scss, theme/style-dark.scss, theme/custom-nav-dark.scss, theme/callouts-dark.scss, theme/sort-ui-dark.scss]
    css:
      - theme/global.css
execute: 
  freeze: true
