project:
  type: website
  resources: 
    - "*.jpg"
    - "*.png"
  render: 
    - "*"
    - "!comments/*"

website:
  title: "Zhehao Hu"
  site-url: https://zzzhehao.github.io
  description: "Zhehao Hu's Personal Website"
  
  navbar: 
    left: 
      - text: "About me"
        menu: 
          - text: "Personal"
            href: about-me/aboutme.qmd
          - text: "As a Biology Student"
            href: about-me/asbiologist.qmd
          - text: "As a Photographer"
            href: about-me/asphotographer.qmd
      - text: "Gallery"
        href: gallery/gallery.qmd
      - text: "Posts"
        href: research/posts.qmd
    tools: 
      - icon: github
        href: https://github.com/zzzhehao
        text: "GitHub"
      - icon: instagram
        href: https://instagram.com/zhehao.hu_
    search: true
    background: transparent

format: 
  html:
    theme: 
      - theme/color-code.scss
      - theme/custom-nav.scss